### ISSUE TITLE
install.sh for linux arm is broken 0.7.2

### ISSUE THREAD

**Issue by broken-trigger** [gladiusio/gladius-node#107]
**Describe the bug**
run install.sh and get an error message for not finding 0.7.1 (404 error)

**To Reproduce**
run install.sh and get an error message for not finding 0.7.1

**Expected behavior**
find and install gladius 0.7.2

**Screenshots**
discord

**Desktop (please complete the following information):**
 - OS: raspos some debian
 - Browser none
 - Version current stable branch

**Additional context**

**Comment by alex-godwin** [comment]
This should be fixed now. Let me know if it's still an issue, and I'll re open it.
