### ISSUE TITLE
Unable to setup node on Windows 7 - 64 bit

### ISSUE THREAD

**Issue by mirrormirage0** [gladiusio/gladius-node#43]
1. Installed App succesfully
2. Created wallet 
3. Added Ether from Faucet.
4. On doing gladius create, after entering name, email and wallet password, it drops to command prompt. No errors.

Can't find log files to trouble shoot. No verbose option to get error.

Tested the following
1) Deleted wallet and keys folder, assuming that special character * in the wallet password might be causing the issue. Didn't work
2) Reinstalled app. Didn't work

**Comment by Celo44** [comment]
@mirrormirage0 Thank you for reporting this. I'm spinning up my windows VM now to try and replicate the issue

**Comment by mirrormirage0** [comment]
based on trouble shooting conducted, root cause identified as node unable to fetch IP address.
Marc is on the move to fix!

**Comment by Celo44** [comment]
https://ipv4.myexternalip.com/raw went down for some reason? Regardless I'm going to try and find a way to retrieve the api w/o relying on external api

**Comment by mirrormirage0** [comment]
https://ipv4.myexternalip.com/raw  is accessible from the browser and returns the correct IP address
Gladius client times out while fetching IP
![capture](https://user-images.githubusercontent.com/29485946/41844750-320cd5b6-7882-11e8-8107-2e944eb95207.JPG)

**Comment by Celo44** [comment]
this is solved in version 0.4.0

**Comment by mirrormirage0** [comment]
May I suggest that you keep the issue open, and close once the new version is released and issue verified to be closed ? I can test as soon as the new version is released.

**Comment by mirrormirage0** [comment]
I have tested and  can confirm that the issue is resolved in version 0.4.0
