### ISSUE TITLE
Linux Installer : install path

### ISSUE THREAD

**Issue by dactar** [gladiusio/gladius-node#44]
It could be usefull to have the possibility to change the install path on linux

For instance : 

Gladius will be installed on /usr/local/bin. Please confirm [Y/n] : N
Please enter install path : /some/where
Path /some/where is valid !
Installing...

**Comment by alex-godwin** [comment]
Great idea, will put in a PR soon.

**Comment by alex-godwin** [comment]
@dactar How's that look to you?

**Comment by alex-godwin** [comment]
Closed for inactivity
