### ISSUE TITLE
Could not create Node for account

### ISSUE THREAD

**Issue by Piston82** [gladiusio/gladius-node#48]
HI
Try to star node on Win7

C:\Program Files (x86)\Gladius Node>gladius create
[Gladius] What is your name? Pist****
[Gladius] What is your email? pist*****@gmail.com
[Gladius] Please type your wallet passphrase:  ********
**Could not create Node for account:utils.ControlDaemonHandler/node.CreateNode**

Ropsten dont want to send 1 eth to my wallet:
https://ropsten.etherscan.io/address/0xD05B4B8E4e13C671cf930ca6408E267B62D63068

And I have a mix of upper and lower cases in the account address...!

**Comment by Celo44** [comment]
Cannot create node because you have no ether in your account.

**Comment by Piston82** [comment]
I think so too, but why Ropsten Faucet don't want to send the eth?

**Comment by maltabernardino** [comment]
HI
Try to star node on Win10 PRO

C:\Users\hgmb1>gladius-node init
[Gladius-Node] What's your email? (So we can contact you about the beta):  h******@hotmail.com
[Gladius-Node] What's your first name?  Hugo
[Gladius-Node] Short bio about why you're interested in Gladius:  ***********.
[Gladius-Node] Please make a new ETH wallet and paste your private key (include 0x at the beginning):
[Gladius-Node] Please enter a passphrase for your new PGP keys:
[Gladius-Node] User profile created! You may create a node with gladius-node create
[Gladius-Node] If you'd like to change your information run gladius-node init again

C:\Users\hgmb1>gladius-node create
[Gladius-Node] Please enter the passphrase for your PGP private key:
[Gladius-Node] Creating Node contract, please wait for tx to complete (this might take a couple of minutes)
[Gladius-Node] Transaction: undefined   [Pending]

- It's been over 15 hours

Ropsten dont want to send 1 eth to my wallet:
https://ropsten.etherscan.io/address/0xBE4D2A356fdbE961a91507f8ad26c8fCE6Bf9F9F

And I have a mix of upper and lower cases in the account address...!
