### ISSUE TITLE
Timeout exceeded while creating GPG keys on raspberry pi

### ISSUE THREAD

**Issue by sebastianhutter** [gladiusio/gladius-node#53]
The 2nd `create` process exceeds the 10 seconds timeout limit. The `create` command fails with the following error message and the node is not fully initialized:

```bash
$ gladius create
[Gladius] What is your name? Sebastian Hutter
[Gladius] What is your email? mail@sebastian-hutter.ch
[Gladius] Please type your wallet passphrase:  ********
Post http://localhost:3001/api/keystore/pgp/create: net/http: request canceled (Client.Timeout exceeded while awaiting headers):client.Do/utils.SendRequest/keystore.CreatePGP
```

I assume this happens because the pi is not powerfull enough to create the PGP key and respond to the api request of the cli  in just 10 seconds. 

The keys are created successfully in the end:
```bash
$ sudo ls -l /root/.config/gladius/keys
total 8
-rw------- 1 root root 3456 Jul 22 06:09 private.asc
-rw-r--r-- 1 root root 1691 Jul 22 06:09 public.asc
```

The simplest solution to this issue is to make the 10s timeout configurable with an environment variable.
This would enable to overwrite the timeout value during command execution:

```bash
# run with 10 second timeout
$ gladius create

# run with 30 second timeout
GLADIUS_TIMEOUT=30 gladius create
```

The necessary code changes are required in the utils.go file
https://github.com/gladiusio/gladius-cli/blob/master/utils/utils.go#L52-L54

Example fix (untested)
```golang
// For control over HTTP client headers,
// redirect policy, and other settings,
// create an HTTP client

// get the gladius timeout value, if not specified set it to 10
// Attention: need to add strconv package !
timeout, exists := os.LookupEnv('GLADIUS_TIMEOUT')
if !exists {
    timeout = '10'
}

var client = &http.Client{
	Timeout: time.Second * strconv.Atoi(timeout),
}
```

**Comment by Celo44** [comment]
Fixed in `develop` of gladius-cli https://github.com/gladiusio/gladius-cli/commit/e49cb8d15c66d05aed9311172ae86d1f388f9166
