### ISSUE TITLE
 Loop error about entering passphrase to unlock wallet on Windows (Server 2012 R2) OS.

### ISSUE THREAD

**Issue by Gajendra2017** [gladiusio/gladius-node#59]
I am getting in Loop about entering passphrase to unlock wallet on Windows (Server 2012 R2) OS. Here is the attached screenshot. The message of wallet unlocked & locked is repeated again endlessly.
![untitled 11](https://user-images.githubusercontent.com/42418978/44167120-efc11500-a0ea-11e8-91e7-b035d00f731d.jpg)

**Comment by Polarogeek** [comment]
![sans titre](https://user-images.githubusercontent.com/37263239/44230728-3e7ab780-a19c-11e8-8757-1aacbf46b57b.png)
me too, windows seven

**Comment by Polarogeek** [comment]
![sans titre](https://user-images.githubusercontent.com/37263239/44230785-72ee7380-a19c-11e8-8f91-b9f98f99847d.png)
me too, windows seven

**Comment by Mikurox** [comment]
(MacOS HighSierra v10.13.6)

On my side I forgot my passphrase so did the following as recommended on the Telegram channel:
1) Delete Mac App
2) Delete ~/.config/gladius
3) Re-install Mac App

After re-installing the App and opening the GUI, it stills show me the passphrase field with the value I entered before!! So even uninstall/clean/install keep some info cached.
(I did not try to setup the node again, I just wanted to get rid of the passphrase field first)

<img width="1198" alt="screen shot 2018-08-17 at 17 33 02" src="https://user-images.githubusercontent.com/26358541/44275238-73424980-a244-11e8-831c-60a498ec659b.png">

**Comment by overtfuture** [comment]
@Polarogeek That fix does work, but wanted to point out that deleting a wallet in the future without backing it up will result in loss of any ETH or coins accumulated or transferred. We do have a fix in the works for this passphrase loop that will be in the next version.
