### ISSUE TITLE
Application version number NOT displaying on Windows OS

### ISSUE THREAD

**Issue by Gajendra2017** [gladiusio/gladius-node#60]
The Application version number in the Application Menu —> About Application of Gladius Node Manager is NOT displaying on Windows (Server 2012 R2) OS.

**Comment by omarbassalti** [comment]
The same on Windows 10.

**Comment by overtfuture** [comment]
We're removing the Application menu for the UI and moving the version handling into the Status Page. In the latest release we also have a mechanism to alert users of out of date versions. You should see this pop up after the next version is released.
