### ISSUE TITLE
Taskbar icon not present in proper way

### ISSUE THREAD

**Issue by omarbassalti** [gladiusio/gladius-node#61]
Hi,

after a super user friendly installation on Windows 10, I observed that if the UI is reduced to icon and the software is running in background the icon in the task-bar doesn't appear even if the program is really working in background.

As per attached image self explaing.

![photo](https://user-images.githubusercontent.com/17832088/44300707-2fcc0600-a33e-11e8-9bb4-33096daacebe.jpg)UNITO-UNDERSCORE!2018-08-18!UNITO-UNDERSCORE!23-25-46!

**Comment by broken-trigger** [comment]
Happens also on Win 8.1 64Bit.

**Comment by overtfuture** [comment]
Fixed this in the manager-ui repo, will be in next release
