### ISSUE TITLE
Can't create a passphrase on the seconds step

### ISSUE THREAD

**Issue by pixel375** [gladiusio/gladius-node#62]
I can't get past the second step where you need to create a passphrase.
Just says "There was a problem creating your wallet. Try again later"

New UI on Windows 7 64bit

**Comment by blckwhtx** [comment]
have the same error message

Windows 10 64bit

**Comment by overtfuture** [comment]
Are you getting this error on a fresh install or a migration from a previous beta?

**Comment by rigamortis1980** [comment]
i have the same problem on first try everything went well when i logged back in to my computer it asked for pass phrase entered entered it said wallet unlocked but just goes back to setup screen when i enter everythng the same it gives me that same error when i enter the pass phrase?

**Comment by blckwhtx** [comment]
on a fresh install

**Comment by rigamortis1980** [comment]
On fresh install everything went fine but couldn't get node started even after being approved so I uninstalled that's when I started having problems.

**Comment by pixel375** [comment]
Solution that worked for me:
Uninstall current version (Preferably with Revo Uninstaller Free)
Open Regedit, and use the "Find" function to search and delete everything that has "Gladius" in it.
Reinstall

**Comment by blckwhtx** [comment]
in version 0.6 exactly the same problem. Can it be that the regestration is only possible for those who have registered for the beta? ( https://beta.gladius.io/ )

**Comment by rigamortis1980** [comment]
Its is very possible this is what I am experiencing do you have a link to
the new 0.6 version?

**Comment by blckwhtx** [comment]
have already installed yesterday version 6.0, just with new installation tried without success

**Comment by blckwhtx** [comment]
my solution is that you have to start "gladius-controld.exe" manually then it works

**Comment by aidannd** [comment]
Still having this issue, receiving "There was a problem creating your wallet. Please try again." error message.

**Comment by overtfuture** [comment]
@aidannd Are you still experiencing this issue with version 0.7.0? We've reworked the service management in this release.

**Comment by matthewlilley** [comment]
@overtfuture I left a message about this in the Telegram, but nobody replied, nor even ACK my message.

When installing a fresh copy on Windows 10, everything went smooth, it seemed like everything was working as expected, but then after checking the Edge Daemon logs, I noticed this message.

 "Couldn't sign message with network gateway, wallet could be locked".

I then restarted the app, and to my surprise, a prompt showed saying "Your wallet is currently locked.", and I was being asked for a non-existent password (obviously I've not been asked to set a password yet). I'm having to assume the app creates a wallet for me, in which case, what is the password?

**Comment by aidannd** [comment]
@overtfuture I'm using version 0.6.2, not sure where to download 0.7.0. It's not listed on the Gladius website.

**Comment by matthewlilley** [comment]
@aidannd https://github.com/gladiusio/gladius-node/releases

**Comment by aidannd** [comment]
@matthewlilley @overtfuture Yep this issue is fixed, for me, in the latest release.

**Comment by alex-godwin** [comment]
Great! I'll close the issue out
