### ISSUE TITLE
Wallet Address NOT Copying or Pasting on Windows OS

### ISSUE THREAD

**Issue by Gajendra2017** [gladiusio/gladius-node#63]
The Wallet Tab includes filling up or Copying or Pasting the Wallet Address in the node. But it is NOT working on Windows OS. It remains empty or useless.

**Comment by GaaTY** [comment]
I'm thinking it's related to the Marketplace section too. It's like the new installation/version is not reading the data from the previous installation.

Opened a seperate issue here: https://github.com/gladiusio/gladius-node/issues/64

**Comment by overtfuture** [comment]
I can look into this a bit more. I believe it's an Electron issue that I assumed would be a cross platform fix by adding in the top menu bar. If this is an install over a previous installation it could be the issue. We haven't allocated any time for beta to beta migrations between versions.

**Comment by overtfuture** [comment]
This has been fixed by adding the Edit menu in the Windows Manager UI
