### ISSUE TITLE
Container created with docker-compose never gets out of pending state for pool application

### ISSUE THREAD

**Issue by aniblaze** [gladiusio/gladius-node#66]
A week ago I have created a container with the docker-compose present in the 'ops' folder. Unfortunately the pool application is not being approved. This issue has persisted for a couple of weeks now (even before the latest release).

1. The container is running.
1. The container's IP address are exposed to the outside.
1. <pu.bl.ic.ip>:8080 gives the 'unsupported path' message.

Attached screenshots illustrate my point.
![screenshot1](https://user-images.githubusercontent.com/1271532/44494267-6fab2a00-a66b-11e8-830b-c15c72d392da.png)
![screenshot2](https://user-images.githubusercontent.com/1271532/44494268-6fab2a00-a66b-11e8-999b-bba75e5c10d7.png)
![screenshot3](https://user-images.githubusercontent.com/1271532/44494269-6fab2a00-a66b-11e8-9c3d-4d35b478fda4.png)

**Comment by aniblaze** [comment]
I just did all the steps below to be sure I did everything correct:

1. Removed all volumes, containers, and images from docker
2. Executed docker-compose up -d in gladius-node/ops folder
3. Executed gladius create, which created a test address
4. Transfered ETH to test address using faucet
5. Executed gladius create again, which created the node, and set node data
6. Executed gladius apply on pool 0x3BbEbCe4e6E3E6DFBe70415102e457e4EE2903e3, which succesfully sent an application to the pool
7. Executed gladius check, which is currently stating that my pool application is "pending"
8. Port 8080 and 7946 are accessable from the outside over TCP

**Comment by overtfuture** [comment]
@aniblaze sorry for the long delay, but we will be doing a full push for Docker support in the coming months. What you are seeing though is the pending application status from a pool manager. For automated deployment solutions like Docker, we are going to implement ways for Pools to allow for auto join and Nodes to set up with an auto config. I'm going to close this for now until we officially unveil full Docker support.
