### ISSUE TITLE
Wrong version is displayed with `gladius version`

### ISSUE THREAD

**Issue by sebastianhutter** [gladiusio/gladius-node#75]
* OS: Debian Linux
* Gladius Version: 0.6.1

_Whats happening:_
When I run `gladius version` the wrong version numbers are displayed:

```
$ gladius version
CLI: 0.5.5
CONTROLD: 0.5.3
NETWORKD: 0.5.2
```

_What do you expect:_
I expect that the correct version numbers are displayed when executing the version command.

_Further Information:_
The versions are hardcoded in gladius-cli/commands/nodeCommands.go:

```golang
func version(cmd *cobra.Command, args []string) {
	terminal.Println(ansi.Color("CLI:", "83+hb"), ansi.Color("0.5.5", "255+hb"))
	terminal.Println(ansi.Color("CONTROLD:", "83+hb"), ansi.Color("0.5.3", "255+hb"))
	terminal.Println(ansi.Color("NETWORKD:", "83+hb"), ansi.Color("0.5.2", "255+hb"))
}
```

Instead of hardcoding the values the version command should get the versions from the gladius binaries directly ~~if this is possible~~  we need to expect that networkd/controld etc are not running when the version command is executed

**Comment by overtfuture** [comment]
This is resolved in 0.7.0 and is displaying versions dynamically from each component.
