### ISSUE TITLE
Add cli command to unlock wallet

### ISSUE THREAD

**Issue by sebastianhutter** [gladiusio/gladius-node#79]
OS: Debian Linux
Gladius Version: 0.6.1

_Whats happening:_
After restarting controld the wallet is locked and must be unlocked.
The networkd daemon is unable to sign messages becasuse the wallet is locked:

```bash
WARN[0000] Error updating disk content                   err="Couldn't sign message with contorld, wallet could be locked"
```

To unlock the wallet I have to execute a curl command:

```bash
curl -XPOST localhost:3001/api/keystore/account/open -d '{"passphrase": "123456"}'
```

_What do you expect:_
I expected to have a simply cli command to unlock the wallet instead of having to execute the curl command.
Something like:

```bash
gladius wallet unlock
```

(or so ;-) ) 

In addition, it would be cool if the controld service would look for the wallet key in some file on the system (configurable via config settings) - so we could implement some auto - unlocking of the wallet.

_Further information:_
Nothing

**Comment by bbspike** [comment]
I can unlock the wallet after a restart of controld by by  using gladius check.

Better is indeed to have simple command like wallet unlock.

**Comment by overtfuture** [comment]
Added this into our backlog for wallet management in the CLI. One option right now is to use the `gladius profile` command. This will trigger a wallet unlock without having to input a Pool address. I'mm going to close this to clean up the issues on GitHub but I saved your description for reference, thanks! I would estimate this being implemented within the next few releases.

**Comment by ianzsarmiento1992** [comment]
curl -XPOST localhost:3001/api/keystore/account/open -d '{"passphrase":"123456"}'

remove one space "123456"}'

**Comment by overtfuture** [comment]
@ianzsarmiento1992 that is correct, you can manually curl to open up the wallet. I'll add in some full instructions while we work on getting our new documentation up:

- Run install.sh from repo
- `sudo gladius-guardian install`
- `sudo gladius-guardian start`
- `curl -XPOST localhost:3001/api/keystore/account/open -d '{"passphrase":"123456"}'`

Services should be started and wallet unlocked
