### ISSUE TITLE
upgrade idea .. integrate console output into GUI

### ISSUE THREAD

**Issue by broken-trigger** [gladiusio/gladius-node#84]
For example the old bitcoin QT Client, offers via menue the use of the console mode. For Gladius integrate the output of networkd and controld, so that it is way more easy to find problems under a running node. Could also add the gladius.exe commands. Would also help the stable product not just for beta testing.

**Comment by overtfuture** [comment]
This was added in the latest release (0.7.0) under the Status Tab in the Advanced section.
