### ISSUE TITLE
No pools in the gladius node manager marketplace

### ISSUE THREAD

**Issue by turbowebmaster** [gladiusio/gladius-node#94]
Hi,

I have recently installed the last beta version of gladius node manager on Windows 7 but in the marketplace list I can't see any pool. I also opened tcp ports 8080 and 7946 but it did not solved my issue. Perhaps do I have to open also udp ports? Or is it a bug? Thank you in advance for your replies...

**Comment by overtfuture** [comment]
We added in the Marketplace support to list all Pools in the UI and is working in the latest release (0.7.0). Please re-open if this is still an issue.

**Comment by Pentagrade** [comment]
This behaviour appears to be happening again, was also reported in issue #115
